//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneNoteExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneNoteExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied link to clipboard.
        /// </summary>
        internal static string CopiedLinkToClipboard {
            get {
                return ResourceManager.GetString("CopiedLinkToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Link to Clipboard.
        /// </summary>
        internal static string CopyLinkToClipboard {
            get {
                return ResourceManager.GetString("CopyLinkToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} in OneNote.
        /// </summary>
        internal static string CreatedNewItemInOneNote {
            get {
                return ResourceManager.GetString("CreatedNewItemInOneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create OneNote Notebook.
        /// </summary>
        internal static string CreateOneNoteNotebook {
            get {
                return ResourceManager.GetString("CreateOneNoteNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create OneNote Page.
        /// </summary>
        internal static string CreateOneNotePage {
            get {
                return ResourceManager.GetString("CreateOneNotePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create OneNote Section.
        /// </summary>
        internal static string CreateOneNoteSection {
            get {
                return ResourceManager.GetString("CreateOneNoteSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create OneNote Section Group.
        /// </summary>
        internal static string CreateOneNoteSectionGroup {
            get {
                return ResourceManager.GetString("CreateOneNoteSectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create + Open.
        /// </summary>
        internal static string CreateOpen {
            get {
                return ResourceManager.GetString("CreateOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Quick Note.
        /// </summary>
        internal static string CreateQuickNote {
            get {
                return ResourceManager.GetString("CreateQuickNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultFilter {
            get {
                return ResourceManager.GetString("DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote Extension.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches must start with a letter or a digit.
        /// </summary>
        internal static string InvalidSearch {
            get {
                return ResourceManager.GetString("InvalidSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section is locked.
        /// </summary>
        internal static string LockedToolTip {
            get {
                return ResourceManager.GetString("LockedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names cannot be empty or contain the characters: {0}.
        /// </summary>
        internal static string NameCannotContainChars {
            get {
                return ResourceManager.GetString("NameCannotContainChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found.
        /// </summary>
        internal static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote Explorer.
        /// </summary>
        internal static string OneNoteExplorer {
            get {
                return ResourceManager.GetString("OneNoteExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In New Window.
        /// </summary>
        internal static string OpenInNewWindow {
            get {
                return ResourceManager.GetString("OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open OneNote.
        /// </summary>
        internal static string OpenOneNote {
            get {
                return ResourceManager.GetString("OpenOneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &quot;{0}&quot; in OneNote.
        /// </summary>
        internal static string OpenXInOneNote {
            get {
                return ResourceManager.GetString("OpenXInOneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create a notebook.
        /// </summary>
        internal static string OrCreateNotebook {
            get {
                return ResourceManager.GetString("OrCreateNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Content.
        /// </summary>
        internal static string PageContent {
            get {
                return ResourceManager.GetString("PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is in a recycle bin.
        /// </summary>
        internal static string RecycleBinToolTip {
            get {
                return ResourceManager.GetString("RecycleBinToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search OneNote pages.
        /// </summary>
        internal static string SearchOneNotePages {
            get {
                return ResourceManager.GetString("SearchOneNotePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search your OneNote pages.
        /// </summary>
        internal static string SearchPageDefaultEmptyContent {
            get {
                return ResourceManager.GetString("SearchPageDefaultEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Groups.
        /// </summary>
        internal static string SectionGroups {
            get {
                return ResourceManager.GetString("SectionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See &quot;More&quot; for additional commands.
        /// </summary>
        internal static string SeeMoreCommands {
            get {
                return ResourceManager.GetString("SeeMoreCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine top level commands into one.
        /// </summary>
        internal static string Settings_CombineTopLevelCommands {
            get {
                return ResourceManager.GetString("Settings_CombineTopLevelCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show recycle bin items.
        /// </summary>
        internal static string Settings_ShowRecycleBinEntries {
            get {
                return ResourceManager.GetString("Settings_ShowRecycleBinEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        internal static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section is unlocked.
        /// </summary>
        internal static string UnlockedToolTip {
            get {
                return ResourceManager.GetString("UnlockedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has unread changes.
        /// </summary>
        internal static string UnreadToolTip {
            get {
                return ResourceManager.GetString("UnreadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View recent OneNote pages.
        /// </summary>
        internal static string ViewRecentOneNotePages {
            get {
                return ResourceManager.GetString("ViewRecentOneNotePages", resourceCulture);
            }
        }
    }
}
